set_property PACKAGE_PIN L15 [get_ports {LED[1]}]
set_property PACKAGE_PIN L14 [get_ports {LED[0]}]
set_property PACKAGE_PIN H16 [get_ports CLK]
set_property PACKAGE_PIN D20 [get_ports RST]

set_property PACKAGE_PIN U15 [get_ports {SW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports GND]
set_property PACKAGE_PIN M20 [get_ports VCC]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports VCC]
set_property PACKAGE_PIN K18 [get_ports {SW[1]}]
