
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DIN[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DIN[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DIN[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DIN[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DIN[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DIN[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DIN[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DIN[7]}]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/tx_fifo_0_n_4]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/tx_fifo_0_n_5]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/tx_fifo_0_n_6]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/tx_fifo_0_n_7]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/tx_fifo_0_n_8]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/tx_fifo_0_n_9]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/tx_fifo_0_n_10]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/tx_fifo_0_n_11]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/WR]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/rd_spi]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/master_0_n_4]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/master_0_n_5]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/master_0_n_6]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/master_0_n_7]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/master_0_n_8]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/master_0_n_9]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/master_0_n_10]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/master_0_n_11]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/sdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/sdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/sdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/sdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/sdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/sdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/sdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/sdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/sdata_0[0]}]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/wr_spi]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DOUT[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DOUT[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DOUT[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DOUT[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DOUT[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DOUT[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DOUT[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spi_top_0/inst/DOUT[7]}]
set_property MARK_DEBUG true [get_nets design_1_i/spi_top_0/inst/rx_fifo_0_n_1]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 5 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/spi_top_0/inst/slave_0/addr[0]} {design_1_i/spi_top_0/inst/slave_0/addr[1]} {design_1_i/spi_top_0/inst/slave_0/addr[2]} {design_1_i/spi_top_0/inst/slave_0/addr[3]} {design_1_i/spi_top_0/inst/slave_0/addr[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/spi_top_0/inst/DIN[0]} {design_1_i/spi_top_0/inst/DIN[1]} {design_1_i/spi_top_0/inst/DIN[2]} {design_1_i/spi_top_0/inst/DIN[3]} {design_1_i/spi_top_0/inst/DIN[4]} {design_1_i/spi_top_0/inst/DIN[5]} {design_1_i/spi_top_0/inst/DIN[6]} {design_1_i/spi_top_0/inst/DIN[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/spi_top_0/inst/slave_0/rdata[0]} {design_1_i/spi_top_0/inst/slave_0/rdata[1]} {design_1_i/spi_top_0/inst/slave_0/rdata[2]} {design_1_i/spi_top_0/inst/slave_0/rdata[3]} {design_1_i/spi_top_0/inst/slave_0/rdata[4]} {design_1_i/spi_top_0/inst/slave_0/rdata[5]} {design_1_i/spi_top_0/inst/slave_0/rdata[6]} {design_1_i/spi_top_0/inst/slave_0/rdata[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/spi_top_0/inst/sdata[0]} {design_1_i/spi_top_0/inst/sdata[1]} {design_1_i/spi_top_0/inst/sdata[2]} {design_1_i/spi_top_0/inst/sdata[3]} {design_1_i/spi_top_0/inst/sdata[4]} {design_1_i/spi_top_0/inst/sdata[5]} {design_1_i/spi_top_0/inst/sdata[6]} {design_1_i/spi_top_0/inst/sdata[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/spi_top_0/inst/slave_0/data[0]} {design_1_i/spi_top_0/inst/slave_0/data[1]} {design_1_i/spi_top_0/inst/slave_0/data[2]} {design_1_i/spi_top_0/inst/slave_0/data[3]} {design_1_i/spi_top_0/inst/slave_0/data[4]} {design_1_i/spi_top_0/inst/slave_0/data[5]} {design_1_i/spi_top_0/inst/slave_0/data[6]} {design_1_i/spi_top_0/inst/slave_0/data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/spi_top_0/inst/sdata_0[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/spi_top_0/inst/slave_0/cmd]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/spi_top_0/inst/master_0_n_4]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/spi_top_0/inst/master_0_n_5]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/spi_top_0/inst/master_0_n_6]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list design_1_i/spi_top_0/inst/master_0_n_7]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list design_1_i/spi_top_0/inst/master_0_n_8]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/spi_top_0/inst/master_0_n_9]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/spi_top_0/inst/master_0_n_10]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/spi_top_0/inst/master_0_n_11]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/spi_top_0/inst/rd_spi]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list design_1_i/spi_top_0/inst/rx_fifo_0_n_1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list design_1_i/spi_top_0/inst/tx_fifo_0_n_4]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list design_1_i/spi_top_0/inst/tx_fifo_0_n_5]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list design_1_i/spi_top_0/inst/tx_fifo_0_n_6]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list design_1_i/spi_top_0/inst/tx_fifo_0_n_7]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list design_1_i/spi_top_0/inst/tx_fifo_0_n_8]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list design_1_i/spi_top_0/inst/tx_fifo_0_n_9]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list design_1_i/spi_top_0/inst/tx_fifo_0_n_10]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list design_1_i/spi_top_0/inst/tx_fifo_0_n_11]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list design_1_i/spi_top_0/inst/WR]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list design_1_i/spi_top_0/inst/wr_spi]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
