set_property IOSTANDARD LVCMOS33 [get_ports {AN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property PACKAGE_PIN T11 [get_ports {AN[6]}]
set_property PACKAGE_PIN Y14 [get_ports {AN[5]}]
set_property PACKAGE_PIN W14 [get_ports {AN[4]}]
set_property PACKAGE_PIN Y17 [get_ports {AN[3]}]
set_property PACKAGE_PIN Y16 [get_ports {AN[2]}]
set_property PACKAGE_PIN Y19 [get_ports {AN[1]}]
set_property PACKAGE_PIN Y18 [get_ports {AN[0]}]
set_property PACKAGE_PIN T10 [get_ports CA]
set_property PACKAGE_PIN H16 [get_ports CLK]
set_property PACKAGE_PIN M15 [get_ports FRM_ERR]
set_property PACKAGE_PIN N15 [get_ports PAR_ERR]
set_property PACKAGE_PIN D20 [get_ports RST]
set_property PACKAGE_PIN J18 [get_ports RXD]
set_property IOSTANDARD LVCMOS33 [get_ports CA]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports FRM_ERR]
set_property IOSTANDARD LVCMOS33 [get_ports PAR_ERR]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports RXD]


#create_clock -period 8.000 -name CLK -waveform {0.000 4.000} [get_ports CLK]
