set_property IOSTANDARD LVCMOS33 [get_ports CA]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property PACKAGE_PIN Y18 [get_ports {AN[0]}]
set_property PACKAGE_PIN Y19 [get_ports {AN[1]}]
set_property PACKAGE_PIN Y16 [get_ports {AN[2]}]
set_property PACKAGE_PIN Y17 [get_ports {AN[3]}]
set_property PACKAGE_PIN W14 [get_ports {AN[4]}]
set_property PACKAGE_PIN Y14 [get_ports {AN[5]}]
set_property PACKAGE_PIN T11 [get_ports {AN[6]}]
set_property PACKAGE_PIN T10 [get_ports CA]


set_property PACKAGE_PIN M20 [get_ports {DIP_VCC[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIP_VCC[0]}]
set_property PACKAGE_PIN U15 [get_ports {dip[0]}]
set_property PACKAGE_PIN G15 [get_ports {dip[3]}]
set_property PACKAGE_PIN J18 [get_ports {dip[2]}]
set_property PACKAGE_PIN K18 [get_ports {dip[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip[0]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list design_1_i/display_inf_0/inst/enable]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
