set_property PACKAGE_PIN D20 [get_ports a]
set_property PACKAGE_PIN D19 [get_ports b]
set_property PACKAGE_PIN G17 [get_ports r]
set_property IOSTANDARD LVCMOS33 [get_ports r]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports a]
